#!/bin/bash

#USE THIS RUN SCRIPT FOR CONFIG 3 
echo "USAGE: ./run_traces <repl_executable_name>"
REPL_NAME=$1
#basepath
BASEPATH=../
TRACEPATH=../../traces
BINPATH=$BASEPATH/bin
RESULTPATH=$BASEPATH/results

MNAME=`hostname`

 
 #benchmarks
Spec2006benchmarks=( 400.perlbench 416.gamess 435.gromacs 445.gobmk 454.calculix 462.libquantum 471.omnetpp 483.xalancbmk 401.bzip2 429.mcf 436.cactusADM 447.dealII 456.hmmer 464.h264ref 473.astar 403.gcc 433.milc 437.leslie3d 450.soplex 458.sjeng 465.tonto 481.wrf 410.bwaves 434.zeusmp 444.namd 453.povray 459.GemsFDTD 470.lbm 482.sphinx3 )


b403=`echo "$TRACEPATH/${Spec2006benchmarks[15]}.200m.gz"`
b401=`echo "$TRACEPATH/${Spec2006benchmarks[8]}.200m.gz"`
b400=`echo "$TRACEPATH/${Spec2006benchmarks[0]}.200m.gz"`
b416=`echo "$TRACEPATH/${Spec2006benchmarks[1]}.200m.gz"`
b429=`echo "$TRACEPATH/${Spec2006benchmarks[9]}.200m.gz"`
b433=`echo "$TRACEPATH/${Spec2006benchmarks[16]}.200m.gz"`
b434=`echo "$TRACEPATH/${Spec2006benchmarks[23]}.200m.gz"`
b450=`echo "$TRACEPATH/${Spec2006benchmarks[18]}.200m.gz"`
b456=`echo "$TRACEPATH/${Spec2006benchmarks[12]}.200m.gz"`
b459=`echo "$TRACEPATH/${Spec2006benchmarks[26]}.200m.gz"`
b462=`echo "$TRACEPATH/${Spec2006benchmarks[5]}.200m.gz"`
b464=`echo "$TRACEPATH/${Spec2006benchmarks[13]}.200m.gz"`
b470=`echo "$TRACEPATH/${Spec2006benchmarks[27]}.200m.gz"`
b473=`echo "$TRACEPATH/${Spec2006benchmarks[14]}.200m.gz"`
b482=`echo "$TRACEPATH/${Spec2006benchmarks[28]}.200m.gz"`
b483=`echo "$TRACEPATH/${Spec2006benchmarks[7]}.200m.gz"`

 
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b403 $b429 $b433 $b483 > $RESULTPATH/group1_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b429 $b450 $b456 $b482 > $RESULTPATH/group2_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b401 $b434 $b456 $b470 > $RESULTPATH/group3_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b450 $b464 $b473 $b483 > $RESULTPATH/group4_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b401 $b433 $b450 $b462 > $RESULTPATH/group5_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b401 $b450 $b450 $b482 > $RESULTPATH/group6_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b403 $b434 $b450 $b464 > $RESULTPATH/group7_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b403 $b456 $b459 $b473 > $RESULTPATH/group8_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b434 $b456 $b482 $b483 > $RESULTPATH/group9_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b400 $b429 $b473 $b483 > $RESULTPATH/group10_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b400 $b450 $b456 $b462 > $RESULTPATH/group11_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b433 $b434 $b450 $b462 > $RESULTPATH/group12_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b433 $b450 $b470 $b483 > $RESULTPATH/group13_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b433 $b450 $b470 $b462 > $RESULTPATH/group14_$REPL_NAME &
$BINPATH/$REPL_NAME -hide_heartbeat -warmup_instructions 100000000 -simulation_instructions 100000000 -traces $b400 $b416 $b456 $b464 > $RESULTPATH/group15_$REPL_NAME &
